<?php
namespace App\Form;
    use App\Entity\Empresa;
    use Symfony\Component\Form\AbstractType;
    use Symfony\Component\Form\FormBuilderInterface;

    use Symfony\Component\OptionsResolver\OptionsResolver;

    class EmpresaType extends AbstractType
    {
        public function buildForm(FormBuilderInterface $builder, array $options)
        {
            $builder -> add('nome')
                ->add('telefone' )
                ->add('endereco');
           // parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        }

        public function configureOptions(OptionsResolver $resolver)
        {
            $resolver->setDefaults(
                ['data_class'=>Empresa::class]
            );
        }
        public function getBlockPrefix()
        {
            return 'app_bundle_post_type';
        }
    }